image: golang:1.21

stages:
  - test
  - build

test:
  stage: test
  except:
    - tags
  script:
    - go test -v ./...

build:
  stage: build
  except:
    - tags
  script:
    - go build ./cmd/semantic-release/
    - ./semantic-release --dry --allow-no-changes --no-ci
